package com.happwner.desktop

data class UiStrings(
    val title: String,
    val server: String,
    val running: String,
    val stopped: String,
    val lanMode: String,
    val port: String,
    val apply: String,
    val autostart: String,
    val add: String,
    val empty: String,
    val edit: String,
    val delete: String,
    val copy: String,
    val qrCode: String,
    val close: String,
    val cancel: String,
    val save: String,
    val name: String,
    val source: String,
    val ua: String,
    val enabled: String,
    val decodeBase64: String,
    val jsonToUri: String,
    val xrayToSingBox: String,
    val lanWarning: String,
    val lanInterface: String,
    val automaticInterface: String,
    val noLanInterfaces: String,
    val unavailable: String,
    val open: String,
    val exit: String,
    val fullExit: String,
    val check: String,
    val checking: String,
    val checkSuccess: String,
    val localData: String,
    val checkFailed: String,
    val profiles: String,
    val noProfiles: String,
    val response: String,
    val invalidSource: String,
    val invalidPort: String,
    val deleteSubscriptionTitle: String,
    val deleteSubscriptionMessage: String,
    val lastRequest: String,
    val subscriptionsTab: String,
    val settingsTab: String,
    val appearance: String,
    val theme: String,
    val darkTheme: String,
    val lightTheme: String,
    val systemTheme: String,
    val serverSettings: String,
    val applicationSettings: String,
    val subscriptionCount: String,
    val generate: String,
    val useLastHwid: String,
    val noSavedHwid: String,
    val diagnosticsTab: String,
    val diagnosticActivity: String,
    val copyReport: String,
    val reportCopied: String,
    val clearLog: String,
    val noActivity: String,
    val client: String,
    val duration: String,
    val transformations: String,
    val requestType: String,
    val clientRequest: String,
    val manualCheck: String,
    val profileCopy: String,
    val copyProfiles: String,
    val copyingProfiles: String,
    val profilesCopied: String,
    val clipboardFailed: String,
    val provider: String,
    val events: String,
    val traffic: String,
    val used: String,
    val remaining: String,
    val expires: String,
    val unlimited: String,
    val noExpiration: String,
    val contacts: String,
    val supportWithStars: String,
    val originalAuthor: String,
    val desktopAuthor: String,
    val githubProfile: String,
    val githubProject: String,
    val linkOpenFailed: String,
)

fun strings(language: String): UiStrings = if (language == "en") {
    UiStrings(
        "Happwner PC", "Subscription server", "Running", "Stopped", "Home network (LAN)", "Port",
        "Apply", "Start with system", "Add subscription", "No subscriptions yet", "Edit", "Delete",
        "Copy URL", "QR code", "Close", "Cancel", "Save", "Name", "Source URL", "User-Agent", "Enabled",
        "Decode Base64", "JSON to URI", "Xray to sing-box",
        "LAN mode has no authentication. Anyone on your home network who knows a subscription URL can read it.",
        "LAN interface", "Automatic (all interfaces)", "No private IPv4 interfaces found", "unavailable",
        "Open", "Exit", "Exit completely", "Test", "Testing…", "Available", "Local data", "Check failed",
        "Profiles", "No supported profiles found", "Response",
        "Enter a valid HTTP(S) or supported wrapped subscription link",
        "Enter a port from 1024 to 65535",
        "Delete subscription?",
        "“%s” will be removed. This action cannot be undone.",
        "Last request",
        "Subscriptions", "Settings", "Appearance", "Theme", "Dark", "Light", "System",
        "Server", "Application", "Subscriptions",
        "Generate", "Use last", "No previously used HWID",
        "Diagnostics", "Request activity", "Copy report", "Report copied", "Clear log",
        "No requests recorded yet", "Client", "Duration", "Transformations", "Type",
        "Subscription client", "Manual test", "Profile copy", "Copy profiles", "Copying…", "Profiles copied",
        "Could not write to the clipboard", "Provider", "Events",
        "Traffic", "Used", "Remaining", "Expires", "Unlimited", "No expiration",
        "Authors and contacts",
        "If you like the project, please support both the original Happwner and this desktop fork with a GitHub star.",
        "Original Happwner author", "Happwner PC author", "Profile", "Project",
        "Could not open the link in the system browser.",
    )
} else {
    UiStrings(
        "Happwner PC", "Сервер подписок", "Работает", "Остановлен", "Домашняя сеть (LAN)", "Порт",
        "Применить", "Запускать с системой", "Добавить подписку", "Подписок пока нет", "Изменить", "Удалить",
        "Копировать URL", "QR-код", "Закрыть", "Отмена", "Сохранить", "Название", "Исходная ссылка", "User-Agent", "Включена",
        "Декодировать Base64", "JSON в URI", "Xray в sing-box",
        "В LAN-режиме нет авторизации. Любой участник домашней сети, знающий адрес подписки, сможет её получить.",
        "LAN-интерфейс", "Автоматически (все интерфейсы)", "Частные IPv4-интерфейсы не найдены", "недоступен",
        "Открыть", "Выход", "Полностью выйти", "Проверить", "Проверяем…", "Доступна", "Локальные данные", "Ошибка проверки",
        "Профили", "Поддерживаемые профили не найдены", "Ответ",
        "Введите корректную HTTP(S)-ссылку или поддерживаемую обёрнутую подписку",
        "Введите порт от 1024 до 65535",
        "Удалить подписку?",
        "«%s» будет удалена. Это действие нельзя отменить.",
        "Последний запрос",
        "Подписки", "Настройки", "Оформление", "Тема", "Тёмная", "Светлая", "Системная",
        "Сервер", "Приложение", "Подписки",
        "Сгенерировать", "Вставить последний", "Ранее использованный HWID отсутствует",
        "Диагностика", "Журнал обращений", "Скопировать отчёт", "Отчёт скопирован", "Очистить журнал",
        "Обращений пока нет", "Клиент", "Время", "Преобразования", "Тип",
        "Клиент подписки", "Ручная проверка", "Копирование профилей", "Скопировать профили", "Копируем…", "Профили скопированы",
        "Не удалось записать данные в буфер обмена", "Провайдер", "События",
        "Трафик", "Использовано", "Осталось", "Действует до", "Безлимит", "Без срока",
        "Авторы и контакты",
        "Если вам нравится проект, поддержите звёздами на GitHub оригинальный Happwner и этот настольный форк.",
        "Автор оригинального Happwner", "Автор Happwner PC", "Профиль", "Проект",
        "Не удалось открыть ссылку в системном браузере.",
    )
}
