package com.happwner.desktop

data class UiStrings(
    val title: String,
    val server: String,
    val running: String,
    val stopped: String,
    val lanMode: String,
    val port: String,
    val apply: String,
    val autostart: String,
    val add: String,
    val empty: String,
    val edit: String,
    val delete: String,
    val copy: String,
    val qrCode: String,
    val close: String,
    val cancel: String,
    val save: String,
    val name: String,
    val source: String,
    val ua: String,
    val enabled: String,
    val decodeBase64: String,
    val jsonToUri: String,
    val xrayToSingBox: String,
    val lanWarning: String,
    val lanInterface: String,
    val automaticInterface: String,
    val noLanInterfaces: String,
    val unavailable: String,
    val open: String,
    val exit: String,
    val fullExit: String,
    val check: String,
    val checking: String,
    val checkSuccess: String,
    val localData: String,
    val checkFailed: String,
    val profiles: String,
    val noProfiles: String,
    val response: String,
    val invalidSource: String,
    val invalidPort: String,
    val deleteSubscriptionTitle: String,
    val deleteSubscriptionMessage: String,
    val lastRequest: String,
    val subscriptionsTab: String,
    val settingsTab: String,
    val appearance: String,
    val theme: String,
    val darkTheme: String,
    val lightTheme: String,
    val systemTheme: String,
    val serverSettings: String,
    val applicationSettings: String,
    val subscriptionCount: String,
)

fun strings(language: String): UiStrings = if (language == "en") {
    UiStrings(
        "Happwner PC", "Subscription server", "Running", "Stopped", "Home network (LAN)", "Port",
        "Apply", "Start with system", "Add subscription", "No subscriptions yet", "Edit", "Delete",
        "Copy URL", "QR code", "Close", "Cancel", "Save", "Name", "Source URL", "User-Agent", "Enabled",
        "Decode Base64", "JSON to URI", "Xray to sing-box",
        "LAN mode has no authentication. Anyone on your home network who knows a subscription URL can read it.",
        "LAN interface", "Automatic (all interfaces)", "No private IPv4 interfaces found", "unavailable",
        "Open", "Exit", "Exit completely", "Test", "Testing…", "Available", "Local data", "Check failed",
        "Profiles", "No supported profiles found", "Response",
        "Enter a valid HTTP(S) or supported wrapped subscription link",
        "Enter a port from 1024 to 65535",
        "Delete subscription?",
        "“%s” will be removed. This action cannot be undone.",
        "Last request",
        "Subscriptions", "Settings", "Appearance", "Theme", "Dark", "Light", "System",
        "Server", "Application", "Subscriptions",
    )
} else {
    UiStrings(
        "Happwner PC", "Сервер подписок", "Работает", "Остановлен", "Домашняя сеть (LAN)", "Порт",
        "Применить", "Запускать с системой", "Добавить подписку", "Подписок пока нет", "Изменить", "Удалить",
        "Копировать URL", "QR-код", "Закрыть", "Отмена", "Сохранить", "Название", "Исходная ссылка", "User-Agent", "Включена",
        "Декодировать Base64", "JSON в URI", "Xray в sing-box",
        "В LAN-режиме нет авторизации. Любой участник домашней сети, знающий адрес подписки, сможет её получить.",
        "LAN-интерфейс", "Автоматически (все интерфейсы)", "Частные IPv4-интерфейсы не найдены", "недоступен",
        "Открыть", "Выход", "Полностью выйти", "Проверить", "Проверяем…", "Доступна", "Локальные данные", "Ошибка проверки",
        "Профили", "Поддерживаемые профили не найдены", "Ответ",
        "Введите корректную HTTP(S)-ссылку или поддерживаемую обёрнутую подписку",
        "Введите порт от 1024 до 65535",
        "Удалить подписку?",
        "«%s» будет удалена. Это действие нельзя отменить.",
        "Последний запрос",
        "Подписки", "Настройки", "Оформление", "Тема", "Тёмная", "Светлая", "Системная",
        "Сервер", "Приложение", "Подписки",
    )
}
